#!/usr/bin/env python
#
####################################
# Login Text Random Change
# written by Mauro Barincelli
# created 2011.01.15
####################################

import os,random

lines = []
fin = open('/opt/local/bbin/random_login_text.list', 'r')

for line in fin.readlines():
    lines.append(line.strip())
    
linesRandom = random.randint(0, len(lines))
newLoginText =  lines[linesRandom -1]

print newLoginText

theCommand = 'defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "' + newLoginText + '"'
print theCommand

os.system(theCommand)
